version: '2.2'
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    container_name: elastic
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticDB:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

volumes:
  elasticDB:
    driver: local