version: "3.9"

volumes:
  shortener-db-pg:

networks:
  localnet:

services:

#  registry:
#    container_name: registry
#    image: registry:2
#    ports:
#      - 5000:5000
#    restart: always
#    networks:
#      - rentalnet

  postgres:
    container_name: pg-shortener
    image: postgres:13.1
    ports:
      - 5432:5432
    volumes:
      #      - ./initDB:/docker-entrypoint-initdb.d
      #      - /var/lib/postgresql/data:/var/lib/postgresql/data
      - shortener-db-pg:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1110
      POSTGRES_DB:  shotener-db
    restart: always
    networks:
      - localnet

  server:
    container_name: short-srv
    #image: 127.0.0.1:5000/stress-test:latest
    build: .
    ports:
      - 8035:8035
    environment:
      #     Переопределяем переменную окружения установленную в Docerfile.
      SRV_HOST: server
      SRV_PORT: 8035
      SHORTENER_STORE=mem
      #POSTGRES_DSN: "postgres://postgres:1110@postgres/shortener-db?sslmode=disable"
    depends_on:
#      - registry
#      - postgres
    restart: always
    networks:
      - localnet

  client:
    container_name: short-client
    #image: 127.0.0.1:5000/stress-test:latest
    build: .
    ports:
      - 8080:8080
    environment:
      #     Переопределяем переменную окружения установленную в Docerfile.
      SRV_HOST: server
      SRV_PORT: 8035
      CLI_HOST: client
      CLI_PORT: 8080
    depends_on:
      - server
    restart: always
    networks:
      - localnet