version: "3.9"

#volumes:
#  shortener-db-pg:

networks:
  localnet:

services:

#  registry:
#    container_name: registry
#    image: registry:2
#    ports:
#      - 5000:5000
#    restart: always
#    networks:
#      - rentalnet

#  postgres:
#    container_name: pg-shortener
#    image: postgres:13.1
#    ports:
#      - 5432:5432
#    volumes:
#      #      - ./initDB:/docker-entrypoint-initdb.d
#      #      - /var/lib/postgresql/data:/var/lib/postgresql/data
#      - shortener-db-pg:/var/lib/postgresql/data
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: 1110
#      POSTGRES_DB:  shotener-db
#    restart: always
#    networks:
#      - localnet

  server:
    container_name: server
    image: aivlev/shortener-srv:v1.0.0
    build: .
    ports:
      - 8040:8040
    environment:
      #     Переопределяем переменную окружения установленную в Docerfile.
#      SRV_HOST: localhost
      SRV_PORT: 8040
      SHORTENER_STORE: mem
      #POSTGRES_DSN: "postgres://postgres:1110@postgres/shortener-db?sslmode=disable"
#    depends_on:
#      - registry
#      - postgres
    restart: always
    networks:
      - localnet

  client:
    container_name: client
    image: aivlev/shortener-cli:v1.0.0
    build: .
    ports:
      - 8000:8000
    environment:
      #     Переопределяем переменную окружения установленную в Docerfile.
      SRV_HOST: 127.0.0.2
      SRV_PORT: 8040
      CLI_HOST: 127.0.0.1
      CLI_PORT: 8000
    depends_on:
      - server
    restart: always
    networks:
      - localnet