version: '3.9'
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: elastic-7.16.2
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticDB:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.2
    container_name: kibana-7.16.2
    environment:
      SERVER_NAME: kibana.example.org
      ELASTICSEARCH_URL: http://elastic:9200
      ELASTICSEARCH_HOSTS: http://elastic:9200
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601

volumes:
  elasticDB:
    driver: local